### ISSUE TITLE
How to unmarshal from a reader?

### ISSUE THREAD

**Issue by ebuchman** [tendermint/go-amino#101]
Do we really just need to read everything manually one byte at a time or whatever?

Otherwise there's no way to know how long a buffer to create and read into to unmarshal from.

Eg. in Tendermint p2p, we have to read msgPacket. We'll have to

```
read 1 byte - channel ID
read 1 byte - EOF
read length of byte slice
read byte slice
```

**Comment by ebuchman** [comment]
Let's write a convenience function that takes a reader and max number of bytes and provides this functionality

**Comment by ebuchman** [comment]
@odeke-em can you take this on? We need to be able to unmarshal off sockets

**Comment by odeke-em** [comment]
Sure, I am working on this today, thank you for the tag @ebuchman!

**Comment by jaekwon** [comment]
Lets implement these methods (with exact signature) in wire.go.


```golang
func (cdc *Codec) MarshalBinaryLengthPrefied(o interface{}) ([]byte, error) {
	panic("not implemented yet") // XXX
}

func (cdc *Codec) UnmarshalBinaryLengthPrefixed(r io.Reader, ptr interface{}, maxBytes int64) error {
	panic("not implemented yet") // XXX
}
```

**Comment by liamsi** [comment]
This was done and refined in amino too 👍
