### ISSUE TITLE
 allocation size out of range

### ISSUE THREAD

**Issue by ebuchman** [tendermint/go-amino#102]
From Tendermint `types` testing/fuzzing:

--- FAIL: TestTxProofUnchangable (2.08s)
panic: runtime: allocation size out of range [recovered]
        panic: runtime: allocation size out of range

goroutine 51 [running]:
testing.tRunner.func1(0xc4208d2870)
        /Users/ethanbuchman/goRoot/1.9.4/src/testing/testing.go:711 +0x2d2
panic(0x156a980, 0x179e970)
        /Users/ethanbuchman/goRoot/1.9.4/src/runtime/panic.go:491 +0x283
reflect.unsafe_NewArray(0x152ea60, 0x1005530cfb9, 0x152ea60)
        /Users/ethanbuchman/goRoot/1.9.4/src/runtime/malloc.go:858 +0x35
reflect.MakeSlice(0x1a44060, 0x152a860, 0x1005530cfb9, 0x1005530cfb9, 0x6, 0x0, 0x0)
        /Users/ethanbuchman/goRoot/1.9.4/src/reflect/value.go:2067 +0xc7
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire.(*Codec).decodeReflectBinarySlice(0xc420064420, 0xc420b89654, 0x6a, 0x6a, 0xc420f6a270, 0x152a860, 0xc420b79a80, 0x197, 0x14f96ee, 0x5, ...)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire/binary-decode.go:448 +0x3f2
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire.(*Codec)._decodeReflectBinary(0xc420064420, 0xc420b8964e, 0x70, 0x70, 0xc420f6a270, 0x152a860, 0xc420b79a80, 0x197, 0x14f96ee, 0x5, ...)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire/binary-decode.go:120 +0x1db8
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire.(*Codec).decodeReflectBinary(0xc420064420, 0xc420b8964e, 0x70, 0x70, 0xc420f6a270, 0x
152a860, 0xc420b79a80, 0x197, 0x14f96ee, 0x5, ...)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire/binary-decode.go:42 +0x375
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire.(*Codec).decodeReflectBinaryStruct(0xc420064420, 0xc420b8964e, 0x70, 0x70, 0xc420f6a1a0, 0x1580a80, 0xc420b79a80, 0x199, 0x14de493, 0x5, ...)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire/binary-decode.go:493 +0x278
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire.(*Codec)._decodeReflectBinary(0xc420064420, 0xc420b8964e, 0x70, 0x70, 0xc420f6a1a0, 0x1580a80, 0xc420b79a80, 0x199, 0x14de493, 0x5, ...)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire/binary-decode.go:125 +0x1b95
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire.(*Codec).decodeReflectBinary(0xc420064420, 0xc420b8964e, 0x70, 0x70, 0xc420f6a1a0, 0x1580a80, 0xc420b79a80, 0x199, 0x14de493, 0x5, ...)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire/binary-decode.go:42 +0x375
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire.(*Codec).decodeReflectBinaryStruct(0xc420064420, 0xc420b8964e, 0x70, 0x70, 0xc420f6a0d0, 0x15d1d60, 0xc420b79a40, 0x199, 0x0, 0x0, ...)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire/binary-decode.go:493 +0x278
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire.(*Codec)._decodeReflectBinary(0xc420064420, 0xc420b895e0, 0xde, 0xde, 0xc420f6a0d0, 0x15d1d60, 0xc420b79a40, 0x199, 0x0, 0x0, ...)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire/binary-decode.go:125 +0x1b95
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire.(*Codec).decodeReflectBinary(0xc420064420, 0xc420b895e0, 0xde, 0xde, 0xc420f6a0d0, 0x15d1d60, 0xc420b79a40, 0x199, 0x0, 0x0, ...)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire/binary-decode.go:42 +0x375

**Comment by zmanian** [comment]
Seems related.
https://stackoverflow.com/questions/25384640/why-golang-reflect-makeslice-returns-un-addressable-value

**Comment by odeke-em** [comment]
This issue was previously also found from fuzzing, PR previously was https://github.com/tendermint/go-wire/pull/38. Returned from the rewrite.

**Comment by liamsi** [comment]
Not sure if this is still an issue. Seems related:
https://github.com/tendermint/go-amino/blob/2106ca61d91029c931fd54968c2bb02dc96b1412/byteslice_test.go#L34-L45

**Comment by liamsi** [comment]
The API changed substantially and the current reader unmarshaller seem to detect overflows.
