### ISSUE TITLE
How does JSON work?

### ISSUE THREAD

**Issue by ebuchman** [tendermint/go-amino#105]
Looking at the tests I see the `_df` and `_v` fields.

Is this really what we want users to be seeing in their genesis files and over RPC? 

Can we get the old format with `type` and `value` back ?

**Comment by odeke-em** [comment]
@ebuchman
"_df" are the disambiguation/disfix bytes that are necessary when we encode an interface with methods
"_v" are the bytes of the underlying type 

They are used later on while disambiguating to a specific type.

**Comment by liamsi** [comment]
Grep'ing in testfiles, I couldn't find any `_df` or `_v` fields anymore. Looks like this can be closed. Although, I've seen a some vars in the code which begin/end with underscores (mostly `_n` for the number of bytes read, or `bz_`). 
Closing for now. We can easily find most occurrences using golint which I'd like to introduce eventually anyways.
