### ISSUE TITLE
Changed binary format of ABCI messages since tendermint 0.16

### ISSUE THREAD

**Issue by srmo** [tendermint/go-amino#113]
Hi,

we are trying to upgrade jabci to 0.16 (https://github.com/jTendermint/jabci) and we are totally lost on the following behavior:

Up until tendermint 15, the initial message when tendermint connected to the ABCI APP was 
`0x01,0x13,0x22,0x11,0x0a,0x0f,0x30,0x2e,0x31,0x35,0x2e,0x30,0x2d,0x61,0x35,0x62,0x37,0x30,0x33,0x34,0x64,0x01,0x02,0x1a,0x00`
Which translates to varint size 0x01 and therefor message size 0x13 which we could then parse to the appropriate protobuf type.
Now, the initial messages has a completely different prefix:
`0x26,0x22,0x11,0x0a,0x0f,0x30,0x2e,0x31,0x36,0x2e,0x30,0x2d,0x63,0x38,0x61,0x32,0x62,0x64,0x66,0x37,0x04,0x1a,0x00`

Interestingly enough, both messages look the same when counted from 3rd byte in the <= 0.15 version and counted from the 2nd byte in 0.16.
Which after another look show that this is not true but can be explained by changed protobuf definitions. So the culprit is the prefix.
TM16 vs TM15:
PREFIX `0x26  vs 0x01,0x13`

Nothing in the changelog hints on what might be going on here but it looks as if the previous varint approach was dropped in tm 0.16.
We have no idea where this change is coming from and a quick "help" in riot pointed to go-wire, honestely, we have no idea on what libraries to what in the tendermint ecosystem when it comes to the socket protocol.

Can you elaborate on that?

**Comment by srmo** [comment]
Update: OK, figured that we can parse the first message `RequestInfo` when discarding the first byte and then reading the next 19 bytes (ommiting the zero-byte at the end).
So how should we know that 0x26 is the type byte for `RequestInfo`?

**Comment by srmo** [comment]
Update: this seems more an issue of changes in abci/types/messages.go how do they relate to go-wire?

**Comment by ebuchman** [comment]
Terribly sorry about this. It's actually an issue on the ABCI side. See my response here https://github.com/tendermint/abci/issues/205#issuecomment-369783104.

Readme, Changelog, and Specification are updated on abci master.

Sorry again!

**Comment by ebuchman** [comment]
Note that `0x26` is the signed varint encoding of `13`, the length of your message. 

See the updated section on length prefixing in the readme https://github.com/tendermint/abci#socket-tsp

**Comment by srmo** [comment]
Thanks for the clarification. Yeah, I've worked through the messages.go code and figured that I need to parse it as uint64 (gladly, JAVA's protobuf impl has a `parseUint64` ;) ) and then shift it right by 1.
Keep rocking!

EDIT: after your link, it turned out that the protobuf java lib also provides ZigZag de-/encoding. So all is clean and fine now :)
