### ISSUE TITLE
encoder: use Typ3_StructTerm instead of 0x04 when encoding Time for literal reading

### ISSUE THREAD

**Issue by odeke-em** [tendermint/go-amino#116]
I was just auditing the new go-wire on develop and noticed
https://github.com/tendermint/go-wire/blob/3d2fb07b5c65de21d624919c4680b1cd1b2cfe90/encoder.go#L141

with a comment sure,

but in the decoder routine it is 
https://github.com/tendermint/go-wire/blob/3d2fb07b5c65de21d624919c4680b1cd1b2cfe90/decoder.go#L250

For ease of reading, symmetry and auditing, let's use Typ3_StructTerm too.

This is a minor nit.

**Comment by liamsi** [comment]
We got rid of struct-terms.
