### ISSUE TITLE
clean JSON

### ISSUE THREAD

**Issue by jbibla** [tendermint/go-amino#128]
takeaway from full node discussion

```
{
    "type": "xxxx",
    "value": {
         "full": "node",
     }
}
```

**Comment by odeke-em** [comment]
@jolesbi what's the issue here? Could you please add some more context as I wasn't at FullNode? Also it'd be helpful for posterity and other maintainers to read and work on.

**Comment by jaekwon** [comment]
This leaves us the option to support this in the future:

```golang
{
    "@type": "xxxx",
    "full": "node"
}
```

So, to preserve this ability and semantic meaning of "@", we won't use it now.

**Comment by jaekwon** [comment]
Closed by https://github.com/tendermint/go-amino/pull/129
