### ISSUE TITLE
MarshalJSONIndent

### ISSUE THREAD

**Issue by melekes** [tendermint/go-amino#136]
![screen shot 2018-04-16 at 10 53 12](https://user-images.githubusercontent.com/1282182/38799335-83789af2-4164-11e8-8f0c-e811762c23d1.png)

Would be nice to have MarshalJSON with indent, so we can print json nicely (both when saving json files in Tendermint and alpha).

**Comment by ebuchman** [comment]
done in https://github.com/tendermint/go-amino/pull/140
