### ISSUE TITLE
Error field type descriptions

### ISSUE THREAD

**Issue by rigelrozanski** [tendermint/go-amino#145]
It would be good to nice better error messages, such as the type the prefix bytes represent.
Here is a message I got recently:
```
Expected field type 496E74657266616365, got 3842797465
```
kind of hard to gather much information from this apart from something is wrong with the marshalling

**Comment by melekes** [comment]
Is this amino or tendermint?

**Comment by liamsi** [comment]
I guess that' amino. We'd need to change a few lines like this:
https://github.com/tendermint/go-amino/blob/6e08b1820c845ea684805678b538b405afc0ed9b/binary-decode.go#L682

I'll send a pr later.

I think, in amino_rs we already do as Rigel proposed. This should be consistent in both implementations.
