### ISSUE TITLE
Time encoding JS compatibility

### ISSUE THREAD

**Issue by mappum** [tendermint/go-amino#147]
Time encoding uses nanosecond precision, which makes it really hard to work with in JS. Not because of the number being too large, but because the ISO timestamp strings used in RPC only have up to microsecond precision and that means we would have to brute-force search through 1000 different possible values 😖

The time encoding has a comment about only using millisecond precision JS compatibility, but it's not true anymore (it was true for `go-wire`).
https://github.com/tendermint/go-amino/blob/master/encoder.go#L112-L143

Would be ideal to just have millisecond precision so we can use the JS `Date` type.

**Comment by jaekwon** [comment]
What does this mean?  "ISO timestamp strings used in RPC only have up to microsecond precision"?  Is that something we control?

**Comment by jaekwon** [comment]
If Javascript doesn't support nanosecond precision, it makes sense not to support it in Amino either.  But what would the MarshalAmino type look like?  How would you implement it?

**Comment by jaekwon** [comment]
I think there was some bug with the previous implementation.
If I'm not mistaken, something about not being able to encode/decode the zero year (0) correctly.  I forget exactly though.

**Comment by mappum** [comment]
> What does this mean? "ISO timestamp strings used in RPC only have up to microsecond precision"? Is that something we control?

I mean when go marshals `time.Time` to a string (e.g. `2018-05-05T17:09:38.114154Z`), it only gives millionths (micro) instead of billionths (nano).

> If Javascript doesn't support nanosecond precision, it makes sense not to support it in Amino either. But what would the MarshalAmino type look like? How would you implement it?

I would think the type could just be a uint64 field that represents milliseconds since Jan 1, 1970. Unless you think the components should be in separate fields as they are now (then we could just round the fractional part to the closest millisecond).

**Comment by jaekwon** [comment]
It may have been just the go-fuzz tests that were failing.  So as long as you can make the go-fuzz tests work..., and all edge-cases like year -9999, 0, 1, 9999 etc work... all good.

**Comment by mappum** [comment]
It seems the issue is only present when compiling with go 1.9. I noticed the binary releases were producing timestamp strings with nanosecond precision, so I updated my go installation to 1.10 and now my builds do as well.

So the real issue is that light clients will fail when connecting to full nodes built with go 1.9, but that's not as critical.
