### ISSUE TITLE
Restricted Codec

### ISSUE THREAD

**Issue by rigelrozanski** [tendermint/go-amino#150]
we should define a codec with the limitation of not being able to register new types, such that it could be passed around knowing that nothing new could be registered. 

In addition, a codec which could be 'sealed' after some types have already been registered could be useful

**Comment by rigelrozanski** [comment]
Along with this is would be nice for this restricted keeper (with nothing registered) to be exposed directly through go-amino to act similar to the old go-wire (where you didn't need to define a codec) for simple situations

**Comment by jaekwon** [comment]
ok!  sounds like a good idea.
