### ISSUE TITLE
Usecase of go-amino?

### ISSUE THREAD

**Issue by svaishnavy** [tendermint/go-amino#152]
I'm implementing a prototype decentralized application using Cosmos-SDK and came across this library.

I'm trying to store and retrieve a struct type in the DB backend(leveldb) provided by the SDK
I'm wondering about the performance of continuous marshalling and unmarshalling  at the time of storing and retrieving the struct. Right now I'm using byte encoding.

Consider the struct as having multiple attributes. Even if I want to update any one attribute, I need to update the whole struct. Similarly, to retrieve the attribute I need to unmarshall the entire row. And I believe that this would impact the performance of the applications.

Does Cosmos/Tendermint have any suggested solution for this one? Is go-amino suitable for this kind of usecase?

**Comment by ebuchman** [comment]
Regardless, when you're storing to a db, you'll need to use some kind of serialization. If not Amino, then something else like Protobuf or Gob or whatever. What do you mean by `byte encoding` ? 

Amino is Tendermint's solution to issues with Protobuf.

We will build additionally tooling to make it much faster than it currently is (ie. with auto-generated code).

Technically you can use the SDK without using Amino.

**Comment by svaishnavy** [comment]
Thanks for the response. I think the problem I mentioned has two parts to it.
1. Storing a struct effectively in DB supported by CosmosSDK(currently leveldb).
2. Lazy loading and updating of values in struct.

Let's take an example:
type Foo struct {
   A string
   B uint64
   C bool
    ...
    Z map[string]uint64
}

Let's say I have this struct, which I want to store in DB and manipulate later. The way I do now is
bytes = db.get(key) // returns bytes
foo = deserialize(bytes)
foo.B++
db.put(key, serialize(foo))

So every time I made an update, I need to serialize and deserialize the whole struct. So the question I have is 
1. Will cosmos-sdk have any columnar store which allows storing columns/attributes independently so that updates could be made only to that column(attribute).

2. In absence of the above, I was wondering if it is possible to eliminate the serialize and deserialize step by directly updating the corresponding bytes(in place) and if go-amino provides this sort of facility? This would allow us to lazy load and set the required attributes once we retrieve bytes from DB. And this would be very beneficial for complex applications to reduce CPU usage associated with serialization and deserialization. We still have to fetch the whole bytes from DB though(I/O)

bytes = db.get(key) // returns bytes
foo = from_bytes(bytes)
foo.update_B(foo.get_B + 1)
db.put(key, foo.get_bytes())

When I said byte encoding, I actually meant - serializing and deserializing data to bytes. Sorry for the confusion.

For the time being though after discussing with community on riot chat, I will be using the first method as it is simpler and faster to implement. But just wanted to hear your thoughts on whether go-amino would support lazy loading of attributes from bytes and will have provision to update attributes in place.

Let me know if my question is clear.

**Comment by ebuchman** [comment]
I don't think this will be in the pipeline any time soon. I'd encourage you to open this issue on Cosmos-SDK tho, since it's really an SDK associated issue than go-amino I think :)

**Comment by svaishnavy** [comment]
Sure, I'll create an issue on Cosmos-SDK. Closing this one.
