### ISSUE TITLE
releases break semantic versioning

### ISSUE THREAD

**Issue by ebuchman** [tendermint/go-amino#159]
0.9.10 is breaking and should have been 0.10.0

It also removed the RFC3339Millis, which was publicly exposed and thus is another breaking change that should be in the changelog.

Also its confusing why the releases dont make their way to master

**Comment by jaekwon** [comment]
Ok on the version.

RFC3339Millis shouldn't be used anywhere, as it isn't the right encoding.  Where was it used?

When should they go to master?  I would think that merges to master happen during releases of parent root projects, not for all releases.

**Comment by ebuchman** [comment]
> RFC3339Millis shouldn't be used anywhere, as it isn't the right encoding. Where was it used?

It's used in tendermint/types for canonical json. We can use something else, just should note it.

> When should they go to master? I would think that merges to master happen during releases of parent root projects, not for all releases.

I think non-breaking changes should go to master right away. Breaking changes can wait until the parent is caught up

**Comment by tac0turtle** [comment]
will follow how other repos are working, will nuke develop here and have master be the default branch, closing this issue as its based on a previous version
