### ISSUE TITLE
MustUnmarshalJSON and MustMarshalJSON

### ISSUE THREAD

**Issue by rigelrozanski** [tendermint/go-amino#165]
why not these 2?

**Comment by rigelrozanski** [comment]
would still be useful!

**Comment by liamsi** [comment]
Yes, I agree! Sorry  for letting this slip. 
With the next release! This would be a fairly simple change but I'm busy with other things. Maybe this is sth. @mossid could take over in the meantime?

**Comment by liamsi** [comment]
resolved by #228
