### ISSUE TITLE
Consider providing functions to calculate encoding overhead

### ISSUE THREAD

**Issue by cwgoes** [tendermint/go-amino#187]
Ref https://github.com/tendermint/tendermint/pull/1721#discussion_r195833879

**Comment by liamsi** [comment]
Replied in the tendermint PR comment: https://github.com/tendermint/tendermint/pull/1721/files/3fc0019f429d40860811033cc5315694c9be9ea6#r195889310

**Comment by jaekwon** [comment]
I suggest we close this issue and revisit when we have the Amino golang optimized compiler.
