### ISSUE TITLE
Combined Key/Value Marshalling/Unmarshalling 

### ISSUE THREAD

**Issue by rigelrozanski** [tendermint/go-amino#199]
#postlaunch

Within the SDK one thing that has come up is the ability to store a part of the object in the key and a part of the object in the value, for instance here is a delegation: 

``` golang
type Delegation struct {
	DelegatorAddr sdk.Address 
	ValidatorAddr sdk.Address 
	Shares        sdk.Rat     
	Height        int64       
}
```

For this struct we want to keep `DelegationAddr` and `ValidatorAddr` in the key of a store and `Shares` and `Height` in the value of the store.

We want the key to be in the following format too (just to add some more complexity to this issue):

`{customPrefixByte,DelegatorAddr.Bytes()..., ValidatorAddr.Bytes()... }`

What would be great would if there was some way to tags and a custom key encoding scheme to be able to define 

``` golang
type Delegation struct {
	DelegatorAddr sdk.Address `amino:"key"`
	ValidatorAddr sdk.Address `amino:"key"`
	Shares        sdk.Rat     `amino:"value"`
	Height        int64       `amino:"value"` 
}

func (d Delegation) keyEncoding() []byte {
    return append(append(
                someCustomPrefixByte,
                DelegatorAddr.Bytes()...),
                ValidatorAddr.Bytes()... )`
}

key := cdc.MustMarshalBinaryKey(prefixByte, delegation)
value := cdc.MustMarshalBinaryValue(delegation)

var delegation Delegation
cdc.MustUnmarshalBinary(key, value, &delegation)
```

Now that I'm thinking about it I think there actually may be some way of already accomplishing this if we could include additional arbitrary fields in `MarshalAmino` and `UnmarshalAmino` 

(CC: @xla @alexanderbez)

**Comment by alexanderbez** [comment]
@rigelrozanski seems like a neat idea! With the tags approach, I think there might need to be some explicit semantics of ordinal positions of fields for brevity. Also, could you elaborate on your last statement?

**Comment by alexanderbez** [comment]
Also, due to the bug that was related to this and the nature of appends, I think this is a bit easier to read:

```go
func (d Delegation) keyEncoding []byte {
    return append(
        append(someCustomPrefixByte, d.DelegatorAddr.Bytes()...),
        d.ValidatorAddr.Bytes()...,
    )
}
```

**Comment by xla** [comment]
In general I support the approach of struct tags as they are powerful tools to avoid a lot of custom serialisation code. As @alexanderbez pointed out it might be necessary to have a bit more control in there.  Also the examples should be updated to use the `amino` tag as already established in the codec code.
https://github.com/tendermint/go-amino/blob/2106ca61d91029c931fd54968c2bb02dc96b1412/codec.go#L475

**Comment by rigelrozanski** [comment]
done

**Comment by liamsi** [comment]
As we want to keep full protobuf compatibility, I think this can be closed. Please, re-open if you feel strongly about this.
