### ISSUE TITLE
Is there any available JS-Amino implementation?

### ISSUE THREAD

**Issue by TanNgocDo** [tendermint/go-amino#210]
Or any suggestion for a reference implementation ?

**Comment by liamsi** [comment]
There is no javascript implmentation yet. As we are largely proto3 compatible it should be fairly easy to use an existing JS protobuf library and extend it to be able to handle [registered types](https://github.com/tendermint/go-amino/#amino-spec) (e.g. this protobuf implementation https://github.com/google/protobuf/tree/master/js looks like a 1st choice). 

If you look into implementing such a library we are happy to provide guidance and help. If you don't, me and @faboweb will hopefully look into implementing this soon.

**Comment by TanNgocDo** [comment]
Hi, I have not checked the protobuf js yet. According to my understanding, in protobuf, we define the .pro files and deliver for both encode and decode side. In amino, we don't need to deliver the shema 
? My intention is implementing the js-amino from scratch with reference from Go-amino. But I have not checked the reflection feature of JS yet(I don't have strong exp in JS). Further more there are some different in types system(no pointer in JS) and what is the equal of []byte in Go compare to Buffer(in nodeJS) 
The scenarior to use js-amino is: client(front-end or react-mobile) will use this lib to encode(marshalJSON or MarshalBinary) transaction (and signing , of course) and send the transaction(like StdTx) to Cosmos-sdk(ABCI-app) . Cosmos SDK will unMarsalJSON(or UnMarsalBinary) the receving []byte
Do you think it is possible according to technical aspect ?

**Comment by liamsi** [comment]
In amino the schema is given by the golang structs and sometimes via type aliases (they always reside in our types packages in the repositories). We did not define a amino format (yet) which would be the equivalent to .proto files in protobuf. It could look very similar to protobuf message definitions. Additionally, it would include information about the codec and which types are registered (with which prefix and potenially disfix).
Eventually, we might implement such a format which can be auto-generated by those structs (types) and the codec they are registered in (if any). 

To answer your question: it is certainly doable from a technical point of view.

(related to: https://github.com/tendermint/go-amino/issues/164 and 
https://github.com/tendermint/go-amino/issues/204)

**Comment by TanNgocDo** [comment]
Thanks for your answer. I will try the "implementation from scratch" solution first

**Comment by TanNgocDo** [comment]
@Liamsi  do you have telegram account? sometimes, I will need you suggestion, thanks

**Comment by jaekwon** [comment]
We need to get you in touch with our JS team... will try.

**Comment by TanNgocDo** [comment]
Thanks, I'm in first stage, I'm working on JSON encoding

**Comment by faboweb** [comment]
Feel free to ask whenever you need help. We also want amino-js :)

**Comment by TanNgocDo** [comment]
Should I raise issue on github or contact you directly when I have question?

**Comment by faboweb** [comment]
Whatever you feel like:
My Telegram is @Fabolicious

TanNgocDo <notifications@github.com> schrieb am Mi., 1. Aug. 2018, 15:17:

**Comment by TanNgocDo** [comment]
Cool, Thank you :)

**Comment by TanNgocDo** [comment]
I have implemented the binary encoding with some basic type, it works. The more complicated type(recursion....) needs more time. I will public the code for review when I reach some minor features. By the way, do you have any ideas for adapt "Decorator" and "Composite" design pattern to this library ? I see with some modules technique, it still works. But maybe a suggestion for design is better to have

**Comment by TanNgocDo** [comment]
I wrote a small impmentation with JS: https://github.com/TanNgocDo/Js-Amino . 
There is no unit test right now- it will be added soon. 
To run the test-decode binary, just use: "node codec.js" for experiment. I used go-amino for encode checking. The list of to-do task will be fulfiled soon

**Comment by TanNgocDo** [comment]
OK, now, basically, it can decode complex recursive struct. The int with 32,16,64 bit will be supported

**Comment by ebuchman** [comment]
tagging @keppel @mappum

**Comment by TanNgocDo** [comment]
By the way, do you have intention for amino on difference programming language ?.I see a Rust project.I would like to start the implementation in C++(if I have time). Have you envisioned the use-case of Amino outside of Cosmos?

**Comment by liamsi** [comment]
I guess, we won't have the capacity to work on other implementations ourselves besides the ones you've mentioned. If you plan to implement it on other languages, that would be a very welcomed contribution though! There are usually, two ways on howto implement this: You could start from scratch, or, you could also fork a existing protobuf implementation. Similar to what we are doing in Rust (work in progress): https://github.com/tendermint/amino_rs/pull/12

> Have you envisioned the use-case of Amino outside of Cosmos?

It could be used pretty much everywhere, where you'd use protobuf but find interfaces / registered types more elegant or feasible than the use of proto's oneof. Also we disallow any non-determinism (flaots, maps) per default which makes it more suitable for use-cases where this is important (like in many blockchain related projects).

Do you think we can close this issue by the way? Do you have all the help you need?

**Comment by TanNgocDo** [comment]
Thanks for your suggestion. I can contact with team via telegram or raise an issue. I can close this issues too

**Comment by siman** [comment]
Hi guys, I am developing TM ABCI dapp in Node.js so I also need this js-amino. What is the status of this lib? Is it ready to use or any other implementations for JS/Node?

**Comment by TanNgocDo** [comment]
There are 2 braches, branch master works well with encode and decode , but encoding with 'interface' type has not supported yet. Another branch is ok with encoding complex interface but there is no decoding part. It only takes me around 1-2 days to finish it, but I'm to busy today to write a docu and fulfill it.Could you please checkout the code/raise an issue. I will try my best to fix bugs as soon as possible

**Comment by faboweb** [comment]
Hey @TanNgocDo have you seen https://github.com/irisnet/irisnet-crypto/blob/master/chains/iris/amino.js ?

**Comment by TanNgocDo** [comment]
Thanks @faboweb  . Have it opened full  source code ? I have a quick check, I see it's using Node Js Buffer, may the React-Native mobile use it too ?

**Comment by hleb-albau** [comment]
Still, need js-amino..... 
@TanNgocDo do a great job, maybe we can somehow grant that initiative?
