### ISSUE TITLE
Incompatible encoding with difference versions

### ISSUE THREAD

**Issue by TanNgocDo** [tendermint/go-amino#220]
I check out the branch 0.10.1 and 0.9.9. I found that there are difference results with prefix part :"pb[3] |= byte(typ)" and "pb[3] &= 0xF8" and add(not sure about other encoding types) Is there any special reason for this issue ?

**Comment by liamsi** [comment]
Hi @TanNgocDo. Thanks for raising this issue. Can you specify what you are encoding? Is this part of the work you are doing on your amino JS port? 

We incorporated quite a few breaking changes in 0.10 though. Most notably, we've changed amino to be more protobuf compatible. We do not expect these versions to be compatible.

**Comment by TanNgocDo** [comment]
Thanks for your answer. My first implementation branch in Js-Amino was the reference on go-amino 0.10.1, but the cosmos-sdk we're using for decoding part have dependencies on Amino 0.9.9. It's not a big problem, I created a new branch that supporting the version 0.9.9 on Js-Amino.

**Comment by TanNgocDo** [comment]
By the way, from 0.10, it seems Type3_Interface was commented out. I'm doing some tricky stuff for js-amino to adapt it

**Comment by liamsi** [comment]
Yeah, we probably won't need them anymore. I would recomend that you'd implement the latest amino version instead. It could also be much simple (using a proto fork instead of starting from scratch).
Closing this for now.
