### ISSUE TITLE
Encoding for time should be the same as Google.Protobuf.WellKnownTypes.Timestamp

### ISSUE THREAD

**Issue by ebuchman** [tendermint/go-amino#223]
There is some pretense that we are the same as the Google.Protobuf.WellKnownTypes.Timestamp but turns out we're not.

See the note in https://github.com/tendermint/tendermint/blob/develop/types/proto3/block.proto#L43

And the code in Amino: https://github.com/tendermint/go-amino/blob/faa6e731944e2b7b6a46ad202902851e8ce85bee/encoder.go#L128-L139

We should fix amino so this aligns properly, unless there is a very good reason not to.

**Comment by liamsi** [comment]
same as https://github.com/tendermint/go-amino/issues/208

**Comment by liamsi** [comment]
Closed via #224

**Comment by vicnaum** [comment]
Docs mention this issue as "to be resolved" in a NOTE at **Time** section:
https://github.com/tendermint/tendermint/blob/master/docs/spec/blockchain/blockchain.md

If it's done, the NOTE should be removed from docs.
