### ISSUE TITLE
Rethink go-wire API

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/go-amino#23]
As we are working to design the cosmos-sdk API, I am writing up sample apps, and realized how confusing it can be to explain go-wire to newcomers.  Not just funny things like needing to embed an interface in a struct, but also the api itself. I want to propose that we redesign the public API, hide most of the methods (which can be private), and adapt the rest to match a cleaner interface. I am not proposing here any fundamental changes to the feature set, except cleaning up how things work.

For example, look at the godoc: https://godoc.org/github.com/tendermint/go-wire

Compared with another binary encoding library: https://godoc.org/encoding/gob#pkg-index
Or even the extremely feature (and error) rich json encoding library: https://godoc.org/encoding/json#pkg-index

Not just the giant intro in the beginning, but that gob has about 90% fewer public methods and a very similar functionality (including registering implementations of interfaces). I am not suggesting to use gob instead (it is much larger than go-wire), but to model our API against something standard.

As a strawman, I would suggest something like this:

```
// registration multiple implementations for an interface, similar to go-data, but global
// multiple calls to Interface with the same base will return the same Registrar
type Registrar
  func Interface(base interface{}) Registrar
  func (r Registrar) RegisterImplementation(data interface{}, b byte) Registrar

// if we want to read/write to bytes - eg. ReadBinaryBytes and BinaryBytes
func Marshal(v interface{}) ([]byte, error)
func Unmarshal(data []byte, v interface{}) error

// if we want to read/write to streams of data - eg. ReadBinary and WriteBinary
type Decoder
  func NewDecoder(r io.Reader) *Decoder
  func (dec *Decoder) Decode(v interface{}) error
type Encoder
  func NewEncoder(w io.Writer) *Encoder
  func (enc *Encoder) Encode(v interface{}) error
```

**Comment by cloudhead** [comment]
+1

We don't want users to have to learn an entirely different library just to do binary encoding/decoding. It should be a drop-in for the gob/json stdlibs ideally.

**Comment by ethanfrey** [comment]
Some random thoughts:
https://chadaustin.me/2017/06/json-never-dies-an-efficient-queryable-binary-encoding/
https://github.com/capnproto/go-capnproto2

**Comment by jaekwon** [comment]
You'll see lines of code like `if lmt != 0 && lmt < *n` in reflect.go.  It's there to abort reading the object when e.g. you're trying to allocate for a slice that is larger than the bytes that are remaining to be read.  In other words, if we're reading a byte slice and the first number (length of the slice) read was 10,000,000, but lmt is 500,000, then we know that this structure is Byzantine and can abort right away rather than trying to allocate for a 10M slice.

For complex structures, a naive safety mechanism that e.g. only allows slices of size 100K at most, aren't good either, when you might have embedded slices.

So, we could adopt Unmarshal/Marshal, but I don't think it should have the same function signature... we should be able to pass in some lmt.

The reason for the lmt & *n split has to do with legacy go-wire where reflect.go didn't exist and I had to hand-write all the field encoding/decoding logic by hand... there were less lines of code with the current go-wire method signature.  We don't need to expose that to the end-user anymore.

**Comment by jaekwon** [comment]
I think everything except this allocation-bounds & early abort, can be replaced with the Marshal/Unmarshal/Encoder/Decoder w/ a CounterReader that aborts when too many bytes are read from the underlying reader.  But that isn't allocation-safe.

**Comment by jaekwon** [comment]
Proposal:

**Comment by ethanfrey** [comment]
`Marshal` / `Unmarshal` take a `[]byte` as input and you can calculate the limit from the input and be safe from allocation issues, no need to require it in the API. 

Just like: https://github.com/tendermint/go-wire/blob/master/util.go#L25 

The issue with handling and `io.Reader` is quite valid.

**Comment by ethanfrey** [comment]
One thought from the protobuf docs (which have a similar problem):

If you want to write multiple messages to a single file or stream, it is up to you to keep track of where one message ends and the next begins. The Protocol Buffer wire format is not self-delimiting, so protocol buffer parsers cannot determine where a message ends on their own. The easiest way to solve this problem is to write the size of each message before you write the message itself. When you read the messages back in, you read the size, then read the bytes into a separate buffer, then parse from that buffer. (If you want to avoid copying bytes to a separate buffer, check out the CodedInputStream class (in both C++ and Java) which can be told to limit reads to a certain number of bytes.)
(https://developers.google.com/protocol-buffers/docs/techniques#streaming)

**Comment by jaekwon** [comment]
On second thought, Marshal/Unmarshal takes []byte, which means we know the length of the bytes to be read, so it doesn't require a CounterReader.

My current thinking is that go-wire can absolutely support Marshal/Unmarshal safely.

This leaves the option to change ReadBinary/ReadBinaryPtr into Encode/Decode.  Anyone have any proposal for that?

In any case, Tendermint reactor Receive() passes []bytes anyways, so Marshal/Unmarshal should be completely safe, and is encouraged.

**Comment by liamsi** [comment]
This are some useful suggestions and a good discussion to have. Still closing as the API was reworked / refactored heavily since this was raised.
