### ISSUE TITLE
Make go-data json setup comprehensible

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/go-amino#24]

**Comment by ethanfrey** [comment]
Right now, the go data json api is relatively easy to use, a bit of confusion on Wrap and Unwrap that should be cleaned up, but somewhat decent. 

However, setting up the wrapping struct, adding methods, registration, etc. Is quite confusing. We have a code generator tool to help, but only Frey can make use of it. 

We need to rethink this to make these features easily usable by new developers

**Comment by liamsi** [comment]
Interesting! Closing as go-data was removed AFAIK.
