### ISSUE TITLE
Encoding of a large byteslice causes a runtime panic

### ISSUE THREAD

**Issue by mveytsman** [tendermint/go-amino#25]
The following snippet causes a runtime panic (on go version go1.9 darwin/amd64)

```golang
n, err := int(0), error(nil)
var x []byte
wire.ReadBinary(x, bytes.NewReader([]byte{8, 127, 255, 255, 255, 255, 255, 255, 255}), 0, &n, &err)
```

This is because https://github.com/tendermint/go-wire/blob/5f88da3dbc1a72844e6dfaf274ce87f851d488eb/byteslice.go#L28 allocates a buffer based on the result of `ReadVarInt`, which can be as large as `math.MaxInt64 = 9223372036854775807`. This is larger than the maximum slice size. (according to [this](https://blog.altoros.com/golang-internals-part-6-bootstrapping-and-memory-allocator-initialization.html), the heap size on 64bit architectures is 512gb)

The solution that comes to mind is to make slice lengths int32 instead of int64s. This can be done by casting them after `ReadVarInt`, or by using `ReadInt32` for length-prefixed objects. Either way this gives a max slice length of 2^32-1, or 4GB byteslices. Assuming that's a large enough length --- I'm not familiar enough with the rest of tendermint yet to judge.

If we switch to `ReadInt32`, that will be a protocol change as `[]byte{42}` used to be encoded as `{1,1,42}` now becomes `{0,0,0,1,42}`.

**Comment by odeke-em** [comment]
Great work @mveytsman, also found independently by go-fuzz https://github.com/tendermint/go-wire/issues/37 in Tendermint https://github.com/tendermint/tendermint/issues/722. I'll issue a fix and tests.
