### ISSUE TITLE
Unify GetFoo and ReadFoo along with PutFoo and WriteFoo

### ISSUE THREAD

**Issue by mveytsman** [tendermint/go-amino#27]
the following functions have both a `Read` (from a `Reader`) and a `Get`  (from a `[]byte` buffer) variant

- `GetByteSlice` / `ReadByteSlice`
- `GetBool` / `ReadBool`
- `GetInt16` / `ReadInt16`
- `GetUint16` / `ReadUint16`
- `GetInt23` / `ReadInt32`
- `GetUint32` / `ReadUint32`
- `GetInt64` / `ReadInt64`
- `GetUint64` / `ReadUint64`
- `GetVarint` / `ReadVarint`
- `GetUvarint` / `ReadUvarint`
- `GetString` / `ReadString`

There's similar pairs of `PutFoo` and `WriteFoo` functions as well.

Each of these function pairs contains similar error checking code i.e. the following two snippets are nearly identical:

https://github.com/tendermint/go-wire/blob/5f88da3dbc1a72844e6dfaf274ce87f851d488eb/byteslice.go#L54-L59

https://github.com/tendermint/go-wire/blob/5f88da3dbc1a72844e6dfaf274ce87f851d488eb/byteslice.go#L19-L26

This is a problem as it required the maintenance of the same sanity checks in two places and this code may diverge at some future time when one of the pairs is modified but not the other. There's no security issue but it's a code smell that can cause problems in the future.

Is it possible to merge the pairs above (i.e. by wrapping buffers in a `bytes.NewReader`)?

Side note: I don't see the `Get` variants being used very much, maybe they're dead code?

**Comment by liamsi** [comment]
The API changed a lot since the old wire days. The duplicate checks do not exist in that form anymore.
