### ISSUE TITLE
New implementation for typescript(javascript)

### ISSUE THREAD

**Issue by Thunnini** [tendermint/go-amino#277]
https://github.com/node-a-team/ts-amino
I am a developer from Node A-Team validator. We are currently making an amino implementation by typescript and it will be fully compatible with Javascript. Although [js-amino](https://github.com/cybercongress/js-amino) is useful, I thought of some new ideas to make it better from scratch. Js-amino will be a good competitor to the one I am making right now. Although decoding features are not implemented yet, but I think my library is slightly more advanced in encoding features because I successfully sent a transaction with this [ts-amino](https://github.com/node-a-team/ts-amino) experimentally. 

We are making a general purpose Javascript library for Cosmos-SDK. This library is not only for Cosmos Hub but also for other hubs and zones implemented by Cosmos-SDK as well. 

An early stage version of the library will be introduced soon.

**Comment by tac0turtle** [comment]
this is amazing, we are moving amino to be proto3 compatible in the coming weeks so hoefully this will speed up things and make it easier to work with

**Comment by tac0turtle** [comment]
closing this issue, for now, if you have any questions or comments, please reopen the issue
