### ISSUE TITLE
Panic caused by decoding invalid time.

### ISSUE THREAD

**Issue by mveytsman** [tendermint/go-amino#28]
There's a panic here:
https://github.com/tendermint/go-wire/blob/5f88da3dbc1a72844e6dfaf274ce87f851d488eb/time.go#L23-L25

that can be triggered with malicious user input.

I.e. the following test panics:

```golang

func TestTimeToPanic(t *testing.T) {
	var x time.Time
	n, err := int(0), error(nil)
	theTime := ReadBinary(x, bytes.NewReader([]byte{0, 0, 0, 0, 0, 0, 0, 1}), 8, &n, &err)
	fmt.Println(theTime)
}

```

This is a denial of service vector similar to https://github.com/tendermint/go-wire/issues/25

We should instead do something like `t = t / 1000000 * 1000000` or just error out.

**Comment by liamsi** [comment]
This panic does not exist anymore (in amino):
https://github.com/tendermint/go-amino/blob/a3c8cf329f44cec2d185be2308364f50b78c5401/decoder.go#L195-L259
