### ISSUE TITLE
make LengthPrefixedEncoder

### ISSUE THREAD

**Issue by petabytestorage** [tendermint/go-amino#59]
same as UnlengthPrefixEncoder for block writing array primitives but prepending some kind of integer type in advance to say how many elements

design decision:  do we use the same fixed length int everywhere? like 32 bits maybe?  or do we use varint everywhere?  or do we need multiple interface choices here?

**Comment by liamsi** [comment]
Amino now follows proto3s behaviour. (Lengths are prefixed using a uvarint BTW)
