### ISSUE TITLE
all: go fmt

### ISSUE THREAD

**Issue by odeke-em** [tendermint/go-amino#76]
I just peeked into this code and noticed un-gofmt'd code that has been in since like 2016. Could we please implement a pre/post commit hook  that ensures all *.go files are go fmt'd?

https://github.com/tendermint/go-wire/blob/27be46e25124ddf775e23317a83647ce62a93f6b/expr/expr.go#L2-L766

**Comment by liamsi** [comment]
Currently, only version.go needs a `go fmt` run. Will be fixed with the next release (today hopefully).
