### ISSUE TITLE
Support MarshalWire, UnmarshalWire

### ISSUE THREAD

**Issue by jaekwon** [tendermint/go-amino#85]
MarshalWire() and UnmarshalWire() take the following set of method signature formats:

`(_ MyObject) MarshalWire() (repr <T>, err error)`
`(_ MyObject) UnmarshalWire(repr <T>) (err error)`

For example,

```golang
type Rat struct {
  *big.Rat
}

// RatWire  - Wire Marshalable Rat Struct
type RatWire  struct {
    Numerator   int64 `json:"numerator"`
    Denominator int64 `json:"denominator"`
}

func (r Rat) MarshalJSON() (repr RatWire, err error) {
    ...
}

// UnmarshalJSON - custom implementation of JSON Unmarshal
func (r *Rat) UnmarshalWire(repr RatWire) error {
     ...
}
```

Benefits: Works for all encoding schemes, e.g. even if we were to support say MarshalProto.

**Comment by liamsi** [comment]
Closing as this seems to stem from pre-amino (wire) times.
