### ISSUE TITLE
fuzz testing for go-wire

### ISSUE THREAD

**Issue by odeke-em** [tendermint/go-amino#96]
We've refurbished the go-wire code from the sdk binary and json codec rewrites. It'd nice for us to fuzz all of them with byte inputs(ie decode) as @jaekwon already started fuzzing with structs(encode then decode) as per https://github.com/tendermint/go-wire/blob/dec83f641903b22f039da3974607859715d0377e/reflect_test.go#L242-L463

**Comment by tac0turtle** [comment]
closing this in favor of #288
