### ISSUE TITLE
EncodeTime: fix comment about cast to int32

### ISSUE THREAD

**Issue by odeke-em** [tendermint/go-amino#97]
Currently in the code on develop we have https://github.com/tendermint/go-wire/blob/dec83f641903b22f039da3974607859715d0377e/encoder.go#L126

saying 'this int64 --> int32 is safe.'

However, that's a little bit misleading because t.NanoSecond() returns an int
and the range of nano-seconds is guaranteed to be [0, 999999999]
as per https://golang.org/pkg/time/#Time.Nanosecond

plus the range of int is the same as the range of int32 i.e, -2147483648 to 2147483647.

Perhaps we meant to make that comment

```go
// this int --> int32 is safe as they have the exact same range plus
// nano-seconds are in the range [0, 999999999] < ((1<<32) - 1) .
```

I mention this because I was just auditing the code and preparing for a fuzz so the comment initially misled me into thinking this was something to test as int64 --> int32 is a potential truncation that could have interesting results, but on recalling and then looking up that time.Time.Nanosecond returns an int.

**Comment by liamsi** [comment]
This comment still exist in amino. The suggestion to clarify the comment, is reasonable.
https://github.com/tendermint/go-amino/blob/a3c8cf329f44cec2d185be2308364f50b78c5401/encoder.go#L119

**Comment by liamsi** [comment]
There are several comments (and checks) now that clarify that nanos are in the range [0, 999999999]. This cast probably should be closer to the code where `ns` are actually used though.
