### ISSUE TITLE
UvarintSize is unnecessarily expensive

### ISSUE THREAD

**Issue by odeke-em** [tendermint/go-amino#98]
I was just auditing the code for fuzzing when I noticed that UvarintSize while trying to find the size of an uint64 actually performs a full binary.PutUvarint encoding and then only extracts the number of bytes written.

We can improve this:
In order to count the number of bytes, we can simply deduct off a byte each time i.e 7 bits off each time so for example to count that we have 3 bytes in 0xFFF, our steps will constitute
while n >= 128 ie 0x80, since byte values are from -128 to 127
a) increment i
b) right shift by 7 bits to clear out the byte length that we just counted
thus making this simple algorithm
```go
i := 1
for n >= 0x80 {
   n >>= 7
   i++
}
return i
```

Given these benchmarks at https://gist.github.com/odeke-em/1b0bdd33304ab3190e6a09776880dae9#file-uvarintsize_test-go
```shell
$ benchstat old.txt new.txt 
name    old time/op    new time/op    delta
Size-4     139ns ± 3%      83ns ± 2%  -40.39%         (p=0.000 n=9+10)

name    old alloc/op   new alloc/op   delta
Size-4    0.00B ±NaN%    0.00B ±NaN%     ~     (all samples are equal)

name    old allocs/op  new allocs/op  delta
Size-4     0.00 ±NaN%     0.00 ±NaN%     ~     (all samples are equal)
```
and we gain a ~40% improvement in runtime, plus our function won't have much to clean up on the stack

**Comment by odeke-em** [comment]
I believe perhaps we can also take a look at https://github.com/tendermint/go-wire/blob/dec83f641903b22f039da3974607859715d0377e/encoder.go#L45-L49

**Comment by liamsi** [comment]
This was optimized by @ValarDragon in https://github.com/tendermint/go-amino/pull/225

**Comment by odeke-em** [comment]
Thank you for the follow up @Liamsi! Just for reference that then means that any project using Go-Amino will have to use Go1.9+
